src/components/LayoutFooter/Footer.js
src/components/LayoutHeader/DocSearch.js
src/components/LayoutHeader/Header.js

Issue: #2 
@Zorig shalgaad ogoorei 🙏

header footer components translations

---

content/docs/lists-and-keys.md

Transation for List-and-keys.md

Add traslation for lists-and-keys.md

---

content/docs/rendering-elements.md

Add mongolian translation for rendering-elements.md

---

content/docs/conditional-rendering.md

Add translation for conditional rendering

---

content/community/courses.md

translated courses page in community. Please check translation.

translated courses page in community

---

content/docs/forms.md

Add translation for forms.md

---

content/docs/introducing-jsx.md

Add translation for introducing-jsx

---

content/home/examples/a-component-using-external-plugins.js
content/home/examples/a-component-using-external-plugins.md
content/home/examples/a-simple-component.js
content/home/examples/a-simple-component.md
content/home/examples/a-stateful-component.js
content/home/examples/a-stateful-component.md
content/home/examples/an-application.js
content/home/examples/an-application.md
content/home/marketing/component-based.md
content/home/marketing/declarative.md
content/home/marketing/learn-once-write-anywhere.md
src/pages/index.js

Home page translation

---

content/docs/handling-events.md

Add translation for handling-events.md

---

content/docs/composition-vs-inheritance.md

Add translation for composition-vs-inheritance.md

---

content/docs/hello-world.md

closes #18

---

content/docs/lifting-state-up.md

Add translation for lifting-state-up.md

---

content/docs/react-without-es6.md

Add translation for react without es6

---

content/tutorial/tutorial.md

#15 Tutorial Translation

---

content/docs/hooks-intro.md

Add translation for introducing hooks

---

content/docs/code-splitting.md

Add translation for code-splitting

---

content/docs/reference-react.md

Add translation for React Reference

---

content/community/nav.yml
content/docs/nav.yml

navigations translation

---

content/community/conferences.md
content/community/examples.md
content/docs/hooks-faq.md

translation of examples page in community menu

---

content/docs/state-and-lifecycle.md

#19 state and lifecycle translation

---

content/docs/context.md
content/docs/nav.yml

I have created a pull request to this section Advanced Guide.Context. Please check it.

translated Advanced Guide Context

---

content/docs/reference-dom-elements.md

Add translation for dom-element-reference

---

content/docs/reference-react-dom.md

fix-reference-react-dom-element

---

content/docs/uncontrolled-components.md

Add translation for uncontrolled components

---

content/docs/hooks-rules.md

Add translation for hooks rules

---

content/docs/create-a-new-react-app.md

#72 create-a-new-react-app.md translation

---

content/docs/portals.md

[#102] portals translation

---

content/docs/react-without-jsx.md

#107 react without jsx translation

---

content/docs/faq-ajax.md

[#110] faq-ajax translation

---

content/404.md
content/community/nav.yml
content/community/support.md
content/headerNav.yml

English => Mongolian and Typo correction

---

content/docs/uncontrolled-components.md

Add translation for default values section

---

src/components/Layout/HomeContent.js
src/components/Layout/TopNav/TopNav.tsx

fix: translation HomeContent

---

src/components/Layout/Footer.tsx
src/content/learn/index.md
src/sidebarHome.json
src/sidebarLearn.json

I translated words such as Quick Start.

Translated words such as Quick Start

---

src/content/learn/installation.md

learn/installation хуудсыг орчууллаа. 
#341

learn-installation initial translation

---

src/content/learn/react-developer-tools.md

translate react-developer-tools
